
druid_restoration = {
   "str": 0,
   "int": 0.38,
   "sta": 0,
   "agi": 0,
   "spi": 0.34,
   "spldmg": 1,
   "hastertng": 0.77,
   "critstrkrtng": 0.69,
   "hitrtng": 0,
   "mleatkpwr": 0,
   "rgdatkpwr": 0,
   "armorpenrtng": 0,
   "armor": 0,
   "exprtng": 0,
   "manargn": 0,
   "defrtng": 0,
   "dodgertng": 0,
   "parryrtng": 0,
   "blockrtng": 0,
   "blockamount": 0,
   "resirtng": 0,
   "mledps": 0,
   "mledmgmax": 0,
   "socket": 19,
}
