
priest_discipline = {
   "str": 0,
   "int": 2.73,
   "sta": 0,
   "agi": 0,
   "spi": 1.63,
   "spldmg": 1,
   "hastertng": 0.28,
   "critstrkrtng": 0.75,
   "hitrtng": 0,
   "mleatkpwr": 0,
   "rgdatkpwr": 0,
   "armorpenrtng": 0,
   "armor": 0,
   "exprtng": 0,
   "manargn": 2.05,
   "defrtng": 0,
   "dodgertng": 0,
   "parryrtng": 0,
   "blockrtng": 0,
   "blockamount": 0,
   "resirtng": 0,
   "mledps": 0,
   "mledmgmax": 0,
   "socket": 43,
}
