
rogue_combat = {
   "str": 1.1,
   "int": 0,
   "sta": 0,
   "agi": 1.92,
   "spi": 0,
   "spldmg": 0,
   "hastertng": 1.62,
   "critstrkrtng": 1.68,
   "hitrtng": 1.67,
   "mleatkpwr": 1,
   "armorpenrtng": 1.64,
   "armor": 0,
   "exprtng": 1.99,
   "manargn": 0,
   "defrtng": 0,
   "dodgertng": 0,
   "parryrtng": 0,
   "blockrtng": 0,
   "blockamount": 0,
   "resirtng": 0,
   "mledps": 2.94,
   "mledmgmax": 1,
   "socket": 29.92,
}

