
rogue_combat = {
   "str": 1.05,
   "int": 0,
   "sta": 0,
   "agi": 2.67,
   "spi": 0,
   "spldmg": 0,
   "hastertng": 1.14,
   "critstrkrtng": 0.75,
   "hitrtng": 0.83,
   "mleatkpwr": 1,
   "armorpenrtng": 0,
   "armor": 0,
   "exprtng": 1.3,
   "manargn": 0,
   "mastery": 1.21,
   "dodgertng": 0,
   "parryrtng": 0,
   "blockrtng": 0,
   "blockamount": 0,
   "resirtng": 0,
   "mledps": 3.95,
   "mledmgmax": 2,
   "socket": 29.92,
}

