
template = {
   "str": 0,
   "int": 0,
   "sta": 0,
   "agi": 0,
   "spi": 0,
   "spldmg": 0,
   "hastertng": 0,
   "critstrkrtng": 0,
   "hitrtng": 0,
   "mleatkpwr": 0,
   "rgdatkpwr": 0,
   "armorpenrtng": 0,
   "armor": 0,
   "exprtng": 0,
   "manargn": 0,
   "defrtng": 0,
   "dodgertng": 0,
   "parryrtng": 0,
   "blockrtng": 0,
   "blockamount": 0,
   "resirtng": 0,
   "mledps": 0,
   "mledmgmax": 0,
   "socket": 0,
}
